/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/app/startup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 启动状态。当前无后台初始化流程，直接返回 ready；
         *     后续加入初始化流程后按 starting → ready/error 流转。
         */
        post: operations["startup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 应用提案：整文件覆盖写盘（父目录自动创建），标记 applied。写盘后文件监听自动推送前端刷新。 */
        post: operations["apply_chat_proposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建会话 */
        post: operations["create_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除会话 */
        post: operations["delete_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 会话详情（全部消息） */
        post: operations["get_chat_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 会话列表（最近更新在前） */
        post: operations["list_chat_sessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发送消息并流式生成回复。响应为 SSE（text/event-stream），data 帧为 JSON：
         *     `{"type":"delta","text":"…"}` 正文增量 / `{"type":"thinking","text":"…"}` 思考增量 /
         *     `{"type":"done","message":{…}}` 完成（完整助手消息，含解析出的提案）/
         *     `{"type":"error","message":"…"}` 失败。
         *     客户端断开连接即中止生成（不保存部分回复）。同一会话同时只允许一个生成。
         */
        post: operations["send_chat_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/characters/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建角色卡（骨架）：同名自动追加 -2/-3 序号；返回可直接进入编辑的详情 */
        post: operations["create_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/characters/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 角色详情（单文件简卡：frontmatter 字段 + 正文；目录深卡：index.md + 子文件列表） */
        post: operations["get_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/characters/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 全局人物库角色列表 */
        post: operations["list_characters"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/characters/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 保存角色卡：临时文件 + rename 原子覆盖（同文稿保存）。
         *     宽容策略：解析失败也保存（用户手改中途不丢内容），但返回 parse_error 提示该卡会从列表消失。
         */
        post: operations["save_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profiles/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除档案；删除默认档案时默认项回退到剩余第一个 */
        post: operations["delete_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profiles/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 档案列表（含默认档案指定） */
        post: operations["list_profiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profiles/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 注册/更新档案（同 key 覆盖；首个档案自动成为默认） */
        post: operations["upsert_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profiles/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 测试档案连接（发一个最小真实调用 ping；验证端点 + 密钥 + 模型 + 协议） */
        post: operations["test_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新建项目：把选中的已有文件夹登记为项目（VSCode「打开文件夹」式），并导入记录。
         *     项目显示名写入 .shiro/project.toml 的 name（与文件夹名解耦）；留空则保留已有或用文件夹名。
         */
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/entry/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重命名项目内条目（文件或目录）：同目录改名 */
        post: operations["rename_entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/excerpts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 目录内全部文稿的正文预览（每篇取开头几行，Ulysses 式列表） */
        post: operations["project_excerpts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/file/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建文稿（空文件） */
        post: operations["create_project_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/file/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除文稿：移入项目回收站（.shiro/trash/，可手动恢复） */
        post: operations["remove_project_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/file/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 读取文稿内容 */
        post: operations["read_project_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/file/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 保存文稿：同目录临时文件 + rename 原子覆盖，写入中断不腐蚀已有正文（见 storage.md 备份与快照） */
        post: operations["write_project_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/folder/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建目录（幂等：已存在返回 200） */
        post: operations["create_project_folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/folder/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除目录：空目录直接删除；非空目录移入项目回收站（.shiro/trash/，可手动恢复） */
        post: operations["remove_project_folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 项目列表（history.toml 记录，最近打开在前） */
        post: operations["list_projects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除项目记录（只从 history.toml 移除，不删除文件夹本身） */
        post: operations["remove_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重命名项目：重命名项目文件夹本体，history.toml 记录同步更新 */
        post: operations["rename_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 项目目录树（目录与文稿文件；目录在前，文件名排序） */
        post: operations["project_tree"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 监听项目目录变动：SSE 推送防抖 300ms 后的变更相对路径集合（`.` 开头路径段与临时文件已过滤）。
         *     每帧 data 为 JSON：`{"changed":["正文/a.md"]}`；changed 为空数组表示事件滞后溢出，订阅方应全量刷新。
         *     监听随连接建立而启动、所有订阅断开后停止。
         */
        post: operations["watch_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplyProposalRequest: {
            /** @description 会话 id */
            id: string;
            /** @description 项目根目录绝对路径 */
            path: string;
            /** @description 提案 id（会话内唯一，见消息的 proposals[].id） */
            proposal_id: string;
        };
        ApplyProposalResponse: {
            proposal: components["schemas"]["Proposal"];
        };
        CardFile: {
            /** @description 子文件内容（markdown） */
            body: string;
            /** @description 子文件名（不带扩展名）：soul / speech_patterns / … / limit */
            name: string;
        };
        CharacterDetail: {
            archetype: string[];
            /** @description 正文 markdown（单文件卡：frontmatter 之后全文；深卡：index.md 正文） */
            body: string;
            /** @description 深卡标记（目录形态档案包时为 full） */
            depth?: string | null;
            /** @description 深卡子文件（单文件简卡为空数组；index 正文已在 body） */
            files: components["schemas"]["CardFile"][];
            id: string;
            name: string;
            /** @description 文件原始内容（含 frontmatter，编辑用；深卡为 index.md 原文） */
            raw: string;
            role?: string | null;
            source?: string | null;
            tags: string[];
        };
        CharacterListResponse: {
            characters: components["schemas"]["CharacterSummary"][];
        };
        CharacterSummary: {
            /** @description 原型标签（可多个） */
            archetype: string[];
            /** @description 深卡标记（目录形态档案包时为 full） */
            depth?: string | null;
            /** @description 正文预览（剥离 markdown 标记后取开头） */
            excerpt: string;
            /** @description 角色 id（单文件：db/人物/ 下文件名去掉 .md；深卡：目录名） */
            id: string;
            /**
             * Format: int64
             * @description 文件修改时间（epoch 秒）
             */
            modified: number;
            /** @description 显示名（frontmatter 的 name；缺失回退文件名） */
            name: string;
            /** @description 功能角色（主角 / 对手 / 盟友 / …） */
            role?: string | null;
            /** @description 来源标注（应用的全局原型，如 db://characters/xxx） */
            source?: string | null;
            /** @description 自由标签 */
            tags: string[];
        };
        ChatMessage: {
            /** Format: int64 */
            at: number;
            /** @description user 消息引用的项目文件（相对路径） */
            attachments?: string[];
            /** @description 原始内容（assistant 含 shiro-edit 块，前端渲染时剥离；保留原文供后续轮次引用） */
            content: string;
            /** @description assistant 消息解析出的提案 */
            proposals?: components["schemas"]["Proposal"][];
            /** @description user / assistant */
            role: string;
        };
        ChatProjectRequest: {
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        CreateCharacterRequest: {
            /** @description 角色显示名（写入 frontmatter 的 name） */
            name: string;
        };
        CreateFileRequest: {
            /** @description 项目内相对路径（父目录自动创建） */
            file: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        CreateFolderRequest: {
            /** @description 项目内相对路径（多级自动创建） */
            folder: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        CreateProjectRequest: {
            /** @description 项目显示名（选填；写入 .shiro/project.toml 的 name，留空则保留已有或用文件夹名） */
            name?: string;
            /** @description 项目文件夹绝对路径（须已存在；任意内容的文件夹均可） */
            path: string;
        };
        CreateSessionRequest: {
            /** @description 项目根目录绝对路径 */
            path: string;
            /** @description 会话标题（缺省「新会话」，首条用户消息自动回填） */
            title?: string | null;
        };
        ErrorResponse: {
            message: string;
        };
        ExcerptsRequest: {
            /** @description 项目内相对路径（'' = 项目根） */
            folder: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        ExcerptsResponse: {
            excerpts: components["schemas"]["SheetExcerpt"][];
        };
        FileContent: {
            content: string;
            /**
             * Format: int64
             * @description 修改时间（epoch 秒）
             */
            modified: number;
        };
        GetCharacterRequest: {
            /** @description 角色 id（单文件卡去 .md 的文件名；深卡为目录名） */
            id: string;
        };
        ProfileKeyRequest: {
            /** @description 档案 key */
            key: string;
        };
        ProfileListResponse: {
            /** @description 默认档案 key（无档案时为 null） */
            default_key?: string | null;
            profiles: components["schemas"]["ProfileSummary"][];
        };
        ProfileSummary: {
            api_key_preview?: string | null;
            api_key_set: boolean;
            base_url: string;
            /** @description 档案 key（供应商 preset key） */
            key: string;
            /** @description 该档案当前使用的模型 */
            model: string;
            /** @description 协议：openai | anthropic */
            protocol: string;
            /** @description 思考强度（未启用为 null） */
            thinking?: string | null;
        };
        ProfileTestResponse: {
            /**
             * Format: int64
             * @description 测试耗时（毫秒，成功时返回）
             */
            latency_ms?: number | null;
            message: string;
            ok: boolean;
        };
        ProjectItem: {
            /** @description 目录当前是否存在（已移动/删除的历史项返回 false，前端置灰） */
            exists: boolean;
            /** @description 显示名（目录 basename） */
            name: string;
            /** @description 项目文件夹绝对路径 */
            path: string;
        };
        ProjectListResponse: {
            projects: components["schemas"]["ProjectItem"][];
        };
        /** @description 整文件覆盖提案（模型输出解析而来；applied = 已写盘） */
        Proposal: {
            applied?: boolean;
            /** Format: int64 */
            applied_at?: number | null;
            /** @description 修改后的完整文件内容 */
            content: string;
            /** @description 项目内相对路径 */
            file: string;
            id: string;
        };
        ReadFileRequest: {
            /** @description 项目内相对路径（如 正文/第一卷/001 序章.md） */
            file: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        RemoveFileRequest: {
            /** @description 文稿相对路径 */
            file: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        RemoveFolderRequest: {
            /** @description 项目内相对路径（不允许根目录与 .shiro） */
            folder: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        RemoveProjectRequest: {
            /** @description 要移除记录的项目路径（只删记录，不删文件夹） */
            path: string;
        };
        RenameEntryRequest: {
            /** @description 新名字（文件名含后缀） */
            new_name: string;
            /** @description 项目根目录绝对路径 */
            path: string;
            /** @description 条目相对路径（文件或目录；文件需含后缀） */
            rel: string;
        };
        RenameProjectRequest: {
            /** @description 新名称（即新目录名） */
            new_name: string;
            /** @description 项目当前绝对路径 */
            path: string;
        };
        SaveCharacterRequest: {
            /** @description 完整文件内容（含 frontmatter） */
            content: string;
            /** @description 角色 id（单文件卡去 .md 的文件名；深卡为目录名） */
            id: string;
        };
        SaveCharacterResponse: {
            character?: null | components["schemas"]["CharacterSummary"];
            parse_error?: string | null;
            /** @description 保存后能否仍解析为角色卡（false = frontmatter 缺失/损坏/未标记类型，该卡不进列表） */
            parsed: boolean;
        };
        SendMessageRequest: {
            /** @description 引用的项目文件（相对路径；内容在前端不可见，由 daemon 注入上下文） */
            attachments?: string[];
            /** @description 用户输入原文 */
            content: string;
            /** @description 会话 id */
            id: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        SessionDetail: {
            /** Format: int64 */
            created_at: number;
            id: string;
            messages: components["schemas"]["ChatMessage"][];
            title: string;
            /** Format: int64 */
            updated_at: number;
        };
        SessionListResponse: {
            sessions: components["schemas"]["SessionSummary"][];
        };
        SessionRefRequest: {
            /** @description 会话 id */
            id: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        SessionSummary: {
            /** Format: int64 */
            created_at: number;
            id: string;
            message_count: number;
            title: string;
            /** Format: int64 */
            updated_at: number;
        };
        SheetExcerpt: {
            /** @description 正文预览（markdown 剥离标记后取开头约 160 字；纯文本直接取开头） */
            excerpt: string;
            /** @description 文稿在项目内的相对路径 */
            file: string;
        };
        StartupResponse: {
            status: components["schemas"]["StartupStatus"];
        };
        /** @enum {string} */
        StartupStatus: "starting" | "ready" | "error";
        TreeNode: {
            /** @description 子节点（仅 dir） */
            children?: components["schemas"]["TreeNode"][] | null;
            /** @description 节点类型：folder / file */
            kind: string;
            /**
             * Format: int64
             * @description 文件修改时间（epoch 秒，仅 file）
             */
            modified?: number | null;
            /** @description 节点名（文件含 .md/.markdown/.txt 后缀） */
            name: string;
            /** @description 项目内相对路径 */
            path: string;
        };
        TreeRequest: {
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        TreeResponse: {
            children: components["schemas"]["TreeNode"][];
        };
        UpsertProfileRequest: {
            /** @description 新密钥；缺省或空字符串 = 保留原值（新建档案必填） */
            api_key?: string | null;
            base_url: string;
            /** @description 档案 key（供应商 preset key；同 key 覆盖更新） */
            key: string;
            model: string;
            protocol?: string | null;
            /** @description 思考强度：缺省/空 = 不启用；low / medium / high */
            thinking?: string | null;
        };
        WatchRequest: {
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        WriteFileRequest: {
            content: string;
            /** @description 项目内相对路径 */
            file: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 启动状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartupResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apply_chat_proposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyProposalRequest"];
            };
        };
        responses: {
            /** @description 已写入文件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyProposalResponse"];
                };
            };
            /** @description 非法路径或提案已应用 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话或提案不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description 项目目录不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRefRequest"];
            };
        };
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_chat_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRefRequest"];
            };
        };
        responses: {
            /** @description 会话详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 会话不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_chat_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatProjectRequest"];
            };
        };
        responses: {
            /** @description 会话列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description 项目目录不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    send_chat_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description SSE 事件流（text/event-stream）：data 为 {type: delta|thinking|done|error, …} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 参数错误（目录不存在 / 内容为空 / 模型未配置） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 上一条回复还在生成中 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_character: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description 名称为空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_character: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetCharacterRequest"];
            };
        };
        responses: {
            /** @description 角色详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description 非法 id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 角色不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_characters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色列表（按显示名排序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_character: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCharacterRequest"];
            };
        };
        responses: {
            /** @description 已保存（含解析反馈） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveCharacterResponse"];
                };
            };
            /** @description 非法 id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 角色不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileKeyRequest"];
            };
        };
        responses: {
            /** @description 已删除（含更新后列表） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 档案不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 档案列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsert_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileRequest"];
            };
        };
        responses: {
            /** @description 已保存（含更新后列表） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    test_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileKeyRequest"];
            };
        };
        responses: {
            /** @description 测试结果（ok 标识连通与否，message 说明） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileTestResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 档案不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItem"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_entry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameEntryRequest"];
            };
        };
        responses: {
            /** @description 已重命名 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法或受保护 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 条目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    project_excerpts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExcerptsRequest"];
            };
        };
        responses: {
            /** @description 预览列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcerptsResponse"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFileRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文件已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveFileRequest"];
            };
        };
        responses: {
            /** @description 已删除（移入回收站） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文件不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadFileRequest"];
            };
        };
        responses: {
            /** @description 文稿内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文件不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    write_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteFileRequest"];
            };
        };
        responses: {
            /** @description 已保存，返回新修改时间 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_project_folder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description 目录已存在 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_project_folder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveFolderRequest"];
            };
        };
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法或受保护 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveProjectRequest"];
            };
        };
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameProjectRequest"];
            };
        };
        responses: {
            /** @description 已重命名 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItem"];
                };
            };
            /** @description 名称非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 项目目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标目录已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    project_tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TreeRequest"];
            };
        };
        responses: {
            /** @description 目录树 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description 项目目录不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    watch_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRequest"];
            };
        };
        responses: {
            /** @description SSE 事件流（text/event-stream）：data 为 {"changed":[...]} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 项目目录不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
