/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/app/startup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 启动状态。当前无后台初始化流程，直接返回 ready；
         *     后续加入初始化流程后按 starting → ready/error 流转。
         */
        get: operations["startup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全局人物库角色列表 */
        get: operations["list_characters"];
        put?: never;
        /** 新建角色卡（骨架）：同名自动追加 -2/-3 序号；返回可直接进入编辑的详情 */
        post: operations["create_character"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 角色详情（单文件简卡：frontmatter 字段 + 正文；目录深卡：index.md + 子文件列表） */
        get: operations["get_character"];
        /**
         * 保存角色卡：临时文件 + rename 原子覆盖（同文稿保存）。
         *     宽容策略：解析失败也保存（用户手改中途不丢内容），但返回 parse_error 提示该卡会从列表消失。
         */
        put: operations["save_character"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取角色制作运行设置 */
        get: operations["get_craft_settings"];
        /**
         * 保存角色制作运行设置（逐项可选，未提供的项不改动；调节即生效）。
         *     切片长度只影响之后新建任务的切块，已建任务保持原切片。
         */
        put: operations["save_craft_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表（最新在前；运行中的任务含实时进度快照） */
        get: operations["list_tasks"];
        put?: never;
        /** 创建角色制作任务（导入剧本 + 角色名/别名），创建即后台执行 */
        post: operations["create_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情：完整进度 + 已生成产物 */
        get: operations["get_task"];
        put?: never;
        post?: never;
        /** 删除任务（连同任务目录；运行中不可删） */
        delete: operations["delete_task"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 中止运行中的任务（LLM 流式请求随之断开；可从断点重试） */
        post: operations["abort_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 调用日志列表（轻量摘要；全文走详情端点） */
        get: operations["list_task_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/logs/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 单条调用日志全文（请求 + 响应/错误） */
        get: operations["get_task_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 任务改名 */
        post: operations["rename_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 失败/中断任务从断点重试（跳过已有产物的阶段） */
        post: operations["retry_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 产物保存到人物库（目录形态深卡，db/人物/<id>/） */
        post: operations["save_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 选择闸门：提交段选择后开始分析（全选则全收） */
        post: operations["select_segments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/deconstruct/tasks/{id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务原文与元信息（复制为新制作的表单回填） */
        get: operations["get_task_source"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 档案列表（含默认档案指定） */
        get: operations["list_profiles"];
        put?: never;
        /** 注册/更新档案（同 key 覆盖；首个档案自动成为默认） */
        post: operations["upsert_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profiles/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除档案；删除默认档案时默认项回退到剩余第一个 */
        delete: operations["delete_profile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profiles/{key}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 测试档案连接（发一个最小真实调用 ping；验证端点 + 密钥 + 模型 + 协议） */
        post: operations["test_profile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目列表（history.toml 记录，最近打开在前） */
        get: operations["list_projects"];
        put?: never;
        /**
         * 新建项目：把选中的已有文件夹登记为项目（VSCode「打开文件夹」式），并导入记录。
         *     项目显示名写入 .shiro/project.toml 的 name（与文件夹名解耦）；留空则保留已有或用文件夹名。
         */
        post: operations["create_project"];
        /** 删除项目记录（只从 history.toml 移除，不删除文件夹本身） */
        delete: operations["remove_project"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/dir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新建目录（幂等：已存在返回 200） */
        post: operations["create_project_dir"];
        /** 删除目录：空目录直接删除；非空目录移入项目回收站（.shiro/trash/，可手动恢复） */
        delete: operations["remove_project_dir"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/entry/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重命名项目内条目（文件或目录）：同目录改名 */
        post: operations["rename_entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/excerpts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 目录内全部文稿的正文预览（每篇取开头几行，Ulysses 式列表） */
        get: operations["project_excerpts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取文稿内容 */
        get: operations["read_project_file"];
        /** 保存文稿：同目录临时文件 + rename 原子覆盖，写入中断不腐蚀已有正文（见 storage.md 备份与快照） */
        put: operations["write_project_file"];
        /** 新建文稿（空文件） */
        post: operations["create_project_file"];
        /** 删除文稿：移入项目回收站（.shiro/trash/，可手动恢复） */
        delete: operations["remove_project_file"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重命名项目：重命名项目文件夹本体，history.toml 记录同步更新 */
        post: operations["rename_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目目录树（目录与文稿文件；目录在前，文件名排序） */
        get: operations["project_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 监听项目目录变动：SSE 推送防抖 300ms 后的变更相对路径集合（`.` 开头路径段与临时文件已过滤）。
         *     每帧 data 为 JSON：`{"changed":["正文/a.md"]}`；changed 为空数组表示事件滞后溢出，订阅方应全量刷新。
         *     鉴权走 `?key=` 查询参数（EventSource 无法自定义 header）。监听随连接建立而启动、所有订阅断开后停止。
         */
        get: operations["watch_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CardFile: {
            /** @description 子文件内容（markdown） */
            body: string;
            /** @description 子文件名（不带扩展名）：soul / speech_patterns / … / limit */
            name: string;
        };
        CardFileDto: {
            /** @description 文件内容（markdown） */
            body: string;
            /** @description 文件名（不带扩展名）：soul / speech_patterns / … / index */
            name: string;
        };
        CharacterDetail: {
            archetype: string[];
            /** @description 正文 markdown（单文件卡：frontmatter 之后全文；深卡：index.md 正文） */
            body: string;
            /** @description 深卡标记（目录形态档案包时为 full） */
            depth?: string | null;
            /** @description 深卡子文件（单文件简卡为空数组；index 正文已在 body） */
            files: components["schemas"]["CardFile"][];
            id: string;
            name: string;
            /** @description 文件原始内容（含 frontmatter，编辑用；深卡为 index.md 原文） */
            raw: string;
            role?: string | null;
            source?: string | null;
            tags: string[];
        };
        CharacterListResponse: {
            characters: components["schemas"]["CharacterSummary"][];
        };
        CharacterSummary: {
            /** @description 原型标签（可多个） */
            archetype: string[];
            /** @description 深卡标记（目录形态档案包时为 full） */
            depth?: string | null;
            /** @description 正文预览（剥离 markdown 标记后取开头） */
            excerpt: string;
            /** @description 角色 id（单文件：db/人物/ 下文件名去掉 .md；深卡：目录名） */
            id: string;
            /**
             * Format: int64
             * @description 文件修改时间（epoch 秒）
             */
            modified: number;
            /** @description 显示名（frontmatter 的 name；缺失回退文件名） */
            name: string;
            /** @description 功能角色（主角 / 对手 / 盟友 / …） */
            role?: string | null;
            /** @description 来源标注（应用的全局原型，如 db://characters/xxx） */
            source?: string | null;
            /** @description 自由标签 */
            tags: string[];
        };
        CraftSettings: {
            /**
             * Format: int32
             * @description AI 调用并发上限（[llm] max_concurrency，1-8）
             */
            max_concurrency: number;
            /** @description 制作任务使用的模型档案 key（[llm] default；未配置为 null） */
            model?: string | null;
            /** @description 切块目标切片长度（[deconstruct] segment_chars，字） */
            segment_chars: number;
        };
        CreateCharacterRequest: {
            /** @description 角色显示名（写入 frontmatter 的 name） */
            name: string;
        };
        CreateDirRequest: {
            /** @description 项目内相对路径（多级自动创建） */
            dir: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        CreateFileRequest: {
            /** @description 项目内相对路径（父目录自动创建） */
            file: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
        CreateProjectRequest: {
            /** @description 项目显示名（选填；写入 .shiro/project.toml 的 name，留空则保留已有或用文件夹名） */
            name?: string;
            /** @description 项目文件夹绝对路径（须已存在；任意内容的文件夹均可） */
            path: string;
        };
        CreateTaskRequest: {
            /** @description 别名/其他写法（避免归属遗漏） */
            aliases?: string[];
            /** @description 待分析角色名（主名） */
            character: string;
            /** @description 剧本全文 */
            content: string;
            /** @description 素材名（作品名或文件名） */
            source_name: string;
        };
        ErrorResponse: {
            message: string;
        };
        ExcerptsResponse: {
            excerpts: components["schemas"]["SheetExcerpt"][];
        };
        FileContent: {
            content: string;
            /**
             * Format: int64
             * @description 修改时间（epoch 秒）
             */
            modified: number;
        };
        LogListResponse: {
            logs: components["schemas"]["LogSummary"][];
        };
        /** @description 日志摘要（列表用；请求/响应全文只给长度，正文走详情接口） */
        LogSummary: {
            /** @description 已放弃：任务中止/中断/失败时在飞的调用，结果永远不会回写 */
            abandoned?: boolean;
            /**
             * Format: int64
             * @description 调用发起时间（epoch 秒；pending 条目前端据此秒表自增）
             */
            at: number;
            /** @description 尝试次数（重试追加在同一日志内） */
            attempt_count: number;
            /**
             * Format: int32
             * @description 缓存命中率（%）
             */
            cache_hit_rate?: number | null;
            /** Format: int64 */
            cache_read?: number | null;
            detail: string;
            /** Format: int64 */
            elapsed_ms: number;
            error?: string | null;
            /** @description 是否有思考过程内容 */
            has_thinking?: boolean;
            /**
             * Format: int64
             * @description token 用量汇总（各次尝试求和；无 usage 数据时为 null）
             */
            input_tokens?: number | null;
            node: string;
            ok?: boolean | null;
            /** Format: int64 */
            output_tokens?: number | null;
            request_chars: number;
            response_chars: number;
            segment?: number | null;
            /** Format: int32 */
            seq: number;
        };
        ProfileListResponse: {
            /** @description 默认档案 key（无档案时为 null） */
            default_key?: string | null;
            profiles: components["schemas"]["ProfileSummary"][];
        };
        ProfileSummary: {
            api_key_preview?: string | null;
            api_key_set: boolean;
            base_url: string;
            /** @description 档案 key（供应商 preset key） */
            key: string;
            /** @description 该档案当前使用的模型 */
            model: string;
            /** @description 协议：openai | anthropic */
            protocol: string;
            /** @description 思考强度（未启用为 null） */
            thinking?: string | null;
        };
        ProfileTestResponse: {
            /**
             * Format: int64
             * @description 测试耗时（毫秒，成功时返回）
             */
            latency_ms?: number | null;
            message: string;
            ok: boolean;
        };
        Progress: {
            /** @description 生成中的当前文件（并行波次可能多个；不带扩展名） */
            current_files?: string[];
            error?: string | null;
            files_done?: string[];
            /** Format: int64 */
            finished_at?: number | null;
            /** @description 素材形态（script/prose；探测后回填） */
            form?: string | null;
            /** @description 中止/失败时所在的管线阶段（流程图定位红格用） */
            last_stage?: string | null;
            /** @description 正在生成笔记的段序号（并行时在飞多段；流程图呼吸态） */
            notes_active?: number[];
            notes_done?: number;
            /** @description 解析失败的段序号（降级，不阻断） */
            notes_failed?: number[];
            /** @description 已完成笔记的段序号（流程图逐格标绿用） */
            notes_finished?: number[];
            saved_character_id?: string | null;
            segment_count?: number;
            /** @description 用户选中的段序号（选择闸门回填；空 = 尚未选择） */
            selected?: number[] | null;
            stage: string;
            verified?: null | components["schemas"]["VerifyReport"];
        };
        ProjectItem: {
            /** @description 目录当前是否存在（已移动/删除的历史项返回 false，前端置灰） */
            exists: boolean;
            /** @description 显示名（目录 basename） */
            name: string;
            /** @description 项目文件夹绝对路径 */
            path: string;
        };
        ProjectListResponse: {
            projects: components["schemas"]["ProjectItem"][];
        };
        RemovedQuote: {
            file: string;
            quote: string;
            unit: string;
        };
        RenameEntryRequest: {
            /** @description 新名字（文件名含后缀） */
            new_name: string;
            /** @description 项目根目录绝对路径 */
            path: string;
            /** @description 条目相对路径（文件或目录；文件需含后缀） */
            rel: string;
        };
        RenameProjectRequest: {
            /** @description 新名称（即新目录名） */
            new_name: string;
            /** @description 项目当前绝对路径 */
            path: string;
        };
        RenameTaskRequest: {
            /** @description 新显示名；空串 = 清除自定义名（回退角色名显示） */
            title: string;
        };
        SaveCharacterRequest: {
            /** @description 完整文件内容（含 frontmatter） */
            content: string;
        };
        SaveCharacterResponse: {
            character?: null | components["schemas"]["CharacterSummary"];
            parse_error?: string | null;
            /** @description 保存后能否仍解析为角色卡（false = frontmatter 缺失/损坏/未标记类型，该卡不进列表） */
            parsed: boolean;
        };
        SaveCraftSettingsRequest: {
            /**
             * Format: int32
             * @description AI 调用并发上限（1-8）
             */
            max_concurrency?: number | null;
            /** @description 模型档案 key（需已注册；设为制作任务使用的档案） */
            model?: string | null;
            /** @description 切块目标切片长度（3000-30000 字） */
            segment_chars?: number | null;
        };
        SaveTaskResponse: {
            /** @description 保存后的人物库角色 id（db/人物/<id>/） */
            character_id: string;
        };
        SegmentInfoDto: {
            /** @description 段字符数 */
            chars: number;
            /** @description 开头预览 */
            excerpt: string;
            /** @description 段内是否出现目标角色名/别名（高亮标记） */
            has_name: boolean;
            /** @description 段序号（切块结果中） */
            index: number;
            /** @description 段标识（章节/场次标题或片段 N） */
            label: string;
        };
        SelectSegmentsRequest: {
            /** @description 选中的段序号（切块结果 index；去重后须非空） */
            selected: number[];
        };
        SheetExcerpt: {
            /** @description 正文预览（markdown 剥离标记后取开头约 160 字；纯文本直接取开头） */
            excerpt: string;
            /** @description 文稿在项目内的相对路径 */
            file: string;
        };
        StartupResponse: {
            status: components["schemas"]["StartupStatus"];
        };
        /** @enum {string} */
        StartupStatus: "starting" | "ready" | "error";
        TaskDetail: {
            aliases: string[];
            character: string;
            /** Format: int64 */
            created_at: number;
            /** @description 产物文件（已生成的部分） */
            files: components["schemas"]["CardFileDto"][];
            id: string;
            /** @description 完整进度（阶段/切片数/笔记进度/生成进度/回查报告/用户选择） */
            progress: components["schemas"]["Progress"];
            /** @description 段清单（切块完成后、待选择阶段提供） */
            segments?: components["schemas"]["SegmentInfoDto"][];
            source_name: string;
            /** @description 显示名（用户自定义；None = 前端用角色名兜底） */
            title?: string | null;
        };
        TaskListResponse: {
            tasks: components["schemas"]["TaskSummary"][];
        };
        TaskSourceResponse: {
            aliases: string[];
            character: string;
            /** @description 剧本原文（复制任务时回填） */
            content: string;
            source_name: string;
        };
        TaskSummary: {
            character: string;
            /** Format: int64 */
            created_at: number;
            error?: string | null;
            /** Format: int64 */
            finished_at?: number | null;
            id: string;
            notes_done: number;
            saved_character_id?: string | null;
            segment_count: number;
            source_name: string;
            stage: string;
            /** @description 显示名（用户自定义；None = 前端用角色名兜底） */
            title?: string | null;
        };
        TreeNode: {
            /** @description 子节点（仅 dir） */
            children?: components["schemas"]["TreeNode"][] | null;
            /** @description dir / file */
            kind: string;
            /**
             * Format: int64
             * @description 文件修改时间（epoch 秒，仅 file）
             */
            modified?: number | null;
            /** @description 节点名（文件含 .md/.markdown/.txt 后缀） */
            name: string;
            /** @description 项目内相对路径 */
            path: string;
        };
        TreeResponse: {
            children: components["schemas"]["TreeNode"][];
        };
        UpsertProfileRequest: {
            /** @description 新密钥；缺省或空字符串 = 保留原值（新建档案必填） */
            api_key?: string | null;
            base_url: string;
            /** @description 档案 key（供应商 preset key；同 key 覆盖更新） */
            key: string;
            model: string;
            protocol?: string | null;
            /** @description 思考强度：缺省/空 = 不启用；low / medium / high */
            thinking?: string | null;
        };
        VerifyReport: {
            /** @description 回查通过的引文数 */
            passed: number;
            /** @description 二次失败后被删除的引文（file, quote, unit） */
            removed: components["schemas"]["RemovedQuote"][];
        };
        WriteFileRequest: {
            content: string;
            /** @description 项目内相对路径 */
            file: string;
            /** @description 项目根目录绝对路径 */
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 启动状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartupResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_characters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色列表（按显示名排序） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_character: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description 名称为空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 角色 id（单文件卡去 .md 的文件名；深卡为目录名） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description 非法 id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 角色不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 角色 id（db/人物/ 下文件名去掉 .md） */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCharacterRequest"];
            };
        };
        responses: {
            /** @description 已保存（含解析反馈） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveCharacterResponse"];
                };
            };
            /** @description 非法 id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 角色不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_craft_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraftSettings"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_craft_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCraftSettingsRequest"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CraftSettings"];
                };
            };
            /** @description 参数越界或档案不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description 已创建并开始执行 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description 参数错误（内容为空/角色名为空） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务目录写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 运行中不可删 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    abort_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已中止 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description 任务不在运行中 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_task_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 调用日志列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_task_log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
                /** @description 日志序号 */
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 日志全文 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 日志不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTaskRequest"];
            };
        };
        responses: {
            /** @description 已改名 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retry_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已从断点重启 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description 状态不允许重试（运行中/已完成） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveTaskResponse"];
                };
            };
            /** @description 任务未完成或产物为空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    select_segments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectSegmentsRequest"];
            };
        };
        responses: {
            /** @description 已提交选择并开始分析 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description 非待选择状态/选择为空 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_task_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 原文与元信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSourceResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 档案列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsert_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileRequest"];
            };
        };
        responses: {
            /** @description 已保存（含更新后列表） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 档案 key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除（含更新后列表） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 档案不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    test_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 档案 key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 测试结果（ok 标识连通与否，message 说明） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileTestResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 档案不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItem"];
                };
            };
            /** @description 参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 要移除记录的项目路径（只删记录，不删文件夹） */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_project_dir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDirRequest"];
            };
        };
        responses: {
            /** @description 目录已存在 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove_project_dir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目根目录绝对路径 */
                path: string;
                /** @description 项目内相对路径（不允许根目录与 .shiro） */
                dir: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法或受保护 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_entry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameEntryRequest"];
            };
        };
        responses: {
            /** @description 已重命名 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法或受保护 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 条目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    project_excerpts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目根目录绝对路径 */
                path: string;
                /** @description 项目内相对路径（'' = 项目根） */
                dir: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 预览列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcerptsResponse"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目根目录绝对路径 */
                path: string;
                /** @description 项目内相对路径（如 正文/第一卷/001 序章.md） */
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文稿内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文件不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    write_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteFileRequest"];
            };
        };
        responses: {
            /** @description 已保存，返回新修改时间 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 写入失败 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFileRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文件已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_project_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目根目录绝对路径 */
                path: string;
                /** @description 文稿相对路径 */
                file: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除（移入回收站） */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 路径非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文件不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameProjectRequest"];
            };
        };
        responses: {
            /** @description 已重命名 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectItem"];
                };
            };
            /** @description 名称非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 项目目录不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 目标目录已存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    project_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目根目录绝对路径 */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 目录树 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeResponse"];
                };
            };
            /** @description 项目目录不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    watch_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 项目根目录绝对路径 */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE 事件流（text/event-stream）：data 为 {"changed":[...]}；鉴权走 ?key= 查询参数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 项目目录不存在 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 未鉴权 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
