[package]
name = "shiro-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
clap = { version = "4.6.6", features = ["derive"] }
futures-util = "0.3.34"
notify = "8"
regex = "1.13.1"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls", "stream", "gzip", "brotli", "deflate", "zstd"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
toml = "1.1.5"
tower-http = { version = "0.7.1", features = ["fs", "cors"] }
utoipa = "5.5.0"
utoipa-axum = "0.2.0"
